title: Tivole Blog
email: asgarovkamran@gmail.com

baseurl: ""
url: "https://tivole.github.io"
github_username: tivole
linkedin_username: tivole

# Build settings
theme: minima
plugins:
  - jekyll-feed
